const BASE = import.meta.env.VITE_API_BASE || '/api/v1';
const KEYS = ['accessToken', 'refreshToken', 'user'];
const store = () => localStorage.getItem('refreshToken') ? localStorage : sessionStorage;
export function getSession() { const s = store(), accessToken = s.getItem('accessToken'), refreshToken = s.getItem('refreshToken'), user = s.getItem('user'); return accessToken && refreshToken ? { accessToken, refreshToken, user: user ? JSON.parse(user) : null } : null; }
export function clearSession() { KEYS.forEach(key => { localStorage.removeItem(key); sessionStorage.removeItem(key); }); }
export function setSession(data, persistent = true) { clearSession(); const s = persistent ? localStorage : sessionStorage; s.setItem('accessToken', data.accessToken); s.setItem('refreshToken', data.refreshToken); s.setItem('user', JSON.stringify(data.user)); }
export class ApiError extends Error { constructor(message, status, fields) { super(message); this.status = status; this.fields = fields || {}; } }
async function refresh() { const session = getSession(); if (!session?.refreshToken) throw new ApiError('Your session has ended. Please sign in again.', 401); const r = await fetch(`${BASE}/auth/refresh`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refreshToken: session.refreshToken }) }); const body = await r.json().catch(() => ({})); if (!r.ok) throw new ApiError(body.error?.message || 'Your session has ended. Please sign in again.', r.status, body.error?.fields); store().setItem('accessToken', body.data.accessToken); }
export async function request(path, options = {}, retried = false) { const session = getSession(); const headers = { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...options.headers }; if (session?.accessToken) headers.Authorization = `Bearer ${session.accessToken}`; let r; try { r = await fetch(`${BASE}${path}`, { ...options, headers }); } catch { throw new ApiError('Unable to connect to the server. Please try again.', 0); } if (r.status === 401 && session?.refreshToken && !retried && !path.startsWith('/auth/')) { try { await refresh(); return request(path, options, true); } catch { clearSession(); window.dispatchEvent(new Event('auth:expired')); throw new ApiError('Your session has ended. Please sign in again.', 401); } } if (r.status === 204) return null; const body = await r.json().catch(() => ({})); if (!r.ok) throw new ApiError(body.error?.message || 'Something went wrong. Please try again.', r.status, body.error?.fields); return body.data ?? body; }
export const api = {
  register: data => request('/auth/register', { method: 'POST', body: JSON.stringify(data) }), login: data => request('/auth/login', { method: 'POST', body: JSON.stringify(data) }), logout: () => request('/auth/logout', { method: 'POST' }), dashboard: () => request('/dashboard'),
  customers: search => request(`/customers?limit=100${search ? `&search=${encodeURIComponent(search)}` : ''}`), createCustomer: data => request('/customers', { method: 'POST', body: JSON.stringify(data) }), updateCustomer: (id, data) => request(`/customers/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), deleteCustomer: id => request(`/customers/${id}`, { method: 'DELETE' }),
  interactions: id => request(`/customers/${id}/interactions?limit=100`), createInteraction: (id, data) => request(`/customers/${id}/interactions`, { method: 'POST', body: JSON.stringify(data) }), updateInteraction: (id, data) => request(`/interactions/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), deleteInteraction: id => request(`/interactions/${id}`, { method: 'DELETE' }),
  followUps: id => request(`/customers/${id}/follow-ups?limit=100`), createFollowUp: (id, data) => request(`/customers/${id}/follow-ups`, { method: 'POST', body: JSON.stringify(data) }), updateFollowUp: (id, data) => request(`/follow-ups/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), completeFollowUp: id => request(`/follow-ups/${id}/complete`, { method: 'POST' }), deleteFollowUp: id => request(`/follow-ups/${id}`, { method: 'DELETE' }),
};
